rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    sessions: "users/sessions",
    registrations: "users/registrations"
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # receiver routes
  post "receiver_end/update", to: "receiver_end#update"
  post "receiver_status/update", to: "receiver_status#update"
  patch "receiver_status/update", to: "receiver_status#update"
  post "receiver_outputs/update", to: "receiver_outputs#update"
  patch "receiver_outputs/update", to: "receiver_outputs#update"


  # Define root path
  root "home#index"

  # Route for 'home' page
  get "home", to: "home#index", as: "home"

  # Search route
  get "search", to: "uploads#search"

  # Resources for 'uploads' with custom collection route
  resources :uploads, except: [ :update, :edit ] do
    collection do
      post "search_items"
    end
  end

  # Catch-all route for non-existent pages, to be used unless assets are being compiled
  match "*path", via: :all, to: "application#not_found", constraints: lambda { |req|
    req.path.exclude? "rails/active_storage"
}
end

rails_app/app/views/shared/_dark_light.html.erb
<div data-controller="theme" data-action="change->theme#saveCheckboxState" class="pt-1 transition-all ease-in-out duration-350 delay-200">
  <label>
    <!-- this hidden checkbox controls the state -->
    <input type="checkbox" data-theme-target="checkbox" class="theme-controller hidden" />
    <!-- sun icon -->
    <div id="sun" class="">
      <%= render 'shared/sun' %>
    </div>
    <!-- moon icon -->
    <div id="moon" class="hidden">
      <%= render 'shared/moon' %>
    </div>
  </label>
</div>

rails_app/app/views/shared/_devise_style_layout.html.erb
<%= render 'shared/nav' %>
<div class="bg-white dark:bg-slate-800 h-screen pt-10" >
  <div class="h-auto w-1/2 xl:w-1/3 p-10 mx-auto rounded-lg bg-gray-200 dark:bg-slate-700 shadow-lg text-slate-800 dark:text-slate-200">
    <%= render partial: inner_partial %>
  </div>
</div>

rails_app/app/views/shared/_dropdown.html.erb
<div class="pt-4 pb-1">
  <%= render 'shared/hamburger' %>
  <div class="hidden" id="mobile-menu">
    <%= render 'shared/dropdown_options' %>
  </div>
</div>
<%= link_to 'krixikAppOne', root_path, class: "btn btn-ghost text-xl absolute top-4 right-16 text-slate-800 dark:text-slate-200 lg:hidden"%>
<div class="absolute right-2 top-2 dark:text-white lg:hidden">
  <%= render 'shared/dark_light' %>
</div>

rails_app/app/views/shared/_dropdown_options.html.erb
<div id="dropdown-options">
  <ul class="bg-slate-200 dark:bg-slate-800 dark:text-white text-slate-900 z-[5] w-52 p-2 shadow">
    <li>
      <%= link_to 'Home', root_path, class: current_page?(root_path) ? "link link-hover text-blue-600 bg-blue-100" : "link link-hover text-black dark:text-white" %>
    </li>
    <li>
      <%= link_to 'Search', search_path, class: current_page?(search_path) ? "link link-hover text-blue-600 bg-blue-100" : "link link-hover text-black dark:text-white" %>
    </li>
    <li>
      <%= link_to 'All uploads', uploads_path, class: current_page?(uploads_path) ? "link link-hover text-blue-600 bg-blue-100" : "link link-hover text-black dark:text-white" %>
    </li>
    <li>
      <%= link_to 'New upload', new_upload_path, class: current_page?(new_upload_path) ? "link link-hover text-blue-600 bg-blue-100" : "link link-hover text-black dark:text-white" %>
    </li>
    <% if user_signed_in? %>
      <li>
        <%= link_to 'Profile', edit_user_registration_path, class: current_page?(edit_user_registration_path) ? "link link-hover text-blue-600 bg-blue-100" : "link link-hover text-black dark:text-white" %>
      </li>
      <li>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Log in", new_user_session_path, class: current_page?(new_user_session_path) ? "link link-hover text-blue-600 bg-blue-100" : "link link-hover text-black dark:text-white" %>
      </li>
      <li>
        <%= link_to "Sign up", new_user_registration_path, class: current_page?(new_user_registration_path) ? "link link-hover text-blue-600 bg-blue-100" : "link link-hover text-black dark:text-white" %>
      </li>
    <% end %>
  </ul>
</div>

rails_app/app/views/shared/_functionality_style_layout.html.erb
<%= render 'shared/nav' %>
<div class="h-screen pt-10 pb-10 bg-gray-100 dark:bg-slate-600 border border-gray-500 dark:border-slate-600" >
  <div class="h-auto w-2/3 p-10 mx-auto rounded-lg flex-col bg-gray-300 dark:bg-slate-700 text-slate-800 dark:text-white">
    <%= render partial: inner_partial %>
  </div>
</div>

rails_app/app/views/shared/_hamburger.html.erb
<div role="button" class="btn btn-ghost lg:hidden mt-1 ml-3 text-slate-800 dark:text-slate-200">
  <div id="hamburger-button">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M4 6h16M4 12h8m-8 6h16" />
    </svg>
  </div>
</div>

rails_app/app/views/shared/_inverse_functionality_style_layout.html.erb
<%= render 'shared/nav' %>
<div class="bg-white dark:bg-slate-800 h-screen">
  <div class="bg-white dark:bg-slate-800 h-auto pb-10 pt-12">
    <%= render partial: inner_partial %>
  </div>
</div>

rails_app/app/views/shared/_menu.html.erb
<div class="hidden lg:flex flex-row text-slate-800 dark:text-white">
  <%= link_to 'krixikAppOne', root_path, class: "btn btn-ghost text-xl left-4 top-5 absolute text-slate-800 dark:text-white" %>
  <ul class="flex flex-row space-x-10 items-center justify-start px-1 inset-x-44 w-3/4 absolute">
    <li>
      <%= link_to 'Home', root_path, class: current_page?(root_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
    </li>
    <li>
      <%= link_to 'Search', search_path, class: current_page?(search_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
    </li>
    <li>
      <%= link_to 'All uploads', uploads_path, class: current_page?(uploads_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
    </li>
    <li>
      <%= link_to 'New upload', new_upload_path, class: current_page?(new_upload_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
    </li>
  </ul>
</div>
<div class="hidden lg:flex flex-row text-slate-800 dark:text-white">
  <ul class="px-0.5 right-5 top-3 absolute flex flex-row">
    <% if user_signed_in? %>
      <li class="mx-4 mt-3">
        <%= link_to 'Profile', edit_user_registration_path, class: current_page?(edit_user_registration_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
      </li>
      <li class="mx-4 mt-3">
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li class="mx-3 mt-3">
        <%= link_to "Log in", new_user_session_path, class: current_page?(new_user_session_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
      </li>
      <li class="mx-4 mt-3 me-6">
        <%= link_to "Sign up", new_user_registration_path, class: current_page?(new_user_registration_path) ? "link link-hover text-black bg-fuchsia-300 px-2 py-3 rounded-xl" : "link link-hover hover:text-black hover:bg-indigo-300 hover:px-2 hover:py-3 hover:rounded-xl" %>
      </li>
    <% end %>
    <li class="mx-4">
      <%= render 'shared/dark_light' %>
    </li>
  </ul>
</div>

rails_app/app/views/shared/_moon.html.erb
<svg
  class="swap-on h-10 w-10 fill-current"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24">
  <path
    d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z" />
</svg>

rails_app/app/views/shared/_nav.html.erb
<nav class="relative pb-3 lg:pt-6 lg:pb-6 bg-gray-300 dark:bg-slate-700" id="navbar">
  <%= render 'shared/menu' %>
  <%= render 'shared/dropdown' %>
</nav>

rails_app/app/views/shared/_notifications.html.erb
<% if message %>
  <div
  data-controller="notification"
  data-action="awesome@window->notification#show"
    class="transition transform duration-1000 hidden"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
    >
    <div class="toast toast-top toast-end">
      <div class="alert alert-info">
        <span>
          <%= message %>
        </span>
        <button data-action="notification#hide">Close</button>
      </div>
    </div>
  </div>
<% end %>

rails_app/app/views/shared/_sun.html.erb
<svg
  class="swap-off h-10 w-10 fill-current"
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 24 24">
  <path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z" />
</svg>