rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    sessions: "users/sessions",
    registrations: "users/registrations"
    }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # receiver routes
  post "receiver_end/update", to: "receiver_end#update"
  post "receiver_status/update", to: "receiver_status#update"
  patch "receiver_status/update", to: "receiver_status#update"
  post "receiver_outputs/update", to: "receiver_outputs#update"
  patch "receiver_outputs/update", to: "receiver_outputs#update"


  # Define root path
  root "home#index"

  # Route for 'home' page
  get "home", to: "home#index", as: "home"

  # Search route
  get "search", to: "uploads#search"

  # Resources for 'uploads' with custom collection route
  resources :uploads, except: [ :update, :edit ] do
    collection do
      post "search_items"
    end
  end

  # Catch-all route for non-existent pages, to be used unless assets are being compiled
  match "*path", via: :all, to: "application#not_found", constraints: lambda { |req|
    req.path.exclude? "rails/active_storage"
}
end

rails_app/app/models/upload.rb
class Upload < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name, against: :filename, using: { tsearch: { prefix: true } }

  belongs_to :user

  has_many_attached :files do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ], preprocessed: true
  end

  has_one :status, dependent: :destroy
  has_one :output, dependent: :destroy
  before_save :set_filename

  after_create :create_status
  after_create :create_output

  validates :files, presence: true
  after_commit :check_and_invoke_lambda, on: :create

  private

  def set_filename
    if files.attached? && !files_attached
      if files.count == 1
        self.filename = files.first.filename.to_s
      end
    end
  end

  def check_and_invoke_lambda
    if files.attached? && !files_attached
      # Check if this is the first file being attached
      if files.count == 1
        file_key = files.first.key # Get the key of the first attached file
        # Pass upload_id and user_id to the LambdaInvoker
        ReceiverStart.new.invoke_function(file_key, id, user_id)
        update(files_attached: true)
      end
    end
  end
  def create_status
    Status.create(upload: self)
  end
  def create_output
    Output.create(upload: self)
  end
end

rails_app/app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  rate_limit to: 20, within: 1.minute, only: [ :index ], with: -> { redirect_to root_path, alert: "Too many requests. Please try again" }

  before_action :set_upload, only: %i[show destroy]
  before_action :authenticate_user!, only: %i[show new create destroy]
  before_action :check_request_from_form, only: [ :search_items ]

  def index
    @uploads = Upload.order(created_at: :desc)
    @pagy, @uploads = pagy(@uploads)
  end

  def new
    @upload = Upload.new
  end

  def show
    @upload = Upload.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def create
    @upload = current_user.uploads.build(upload_params)
    if @upload.save
      redirect_to upload_path(@upload), notice: "Upload was successfully created."
    else
      render :new
    end
  end

  def destroy
    @upload.destroy
    redirect_to uploads_url, notice: "Upload was successfully destroyed."
  end

  def search
  end

  def search_items
    @query=search_params["query"]
    @uploads = Upload.search_by_name(@query)
    .where(process_complete: true)
    .limit(10) || []
    @uploads = @uploads.sort_by(&:created_at).reverse
    respond_to do |format|
      format.turbo_stream do
          if @query.blank?
            render turbo_stream: turbo_stream.update("search_results", partial: "uploads/no_search")
          else
            render turbo_stream: turbo_stream.update("search_results", partial: "uploads/search_results", locals: { uploads: @uploads })
          end
        end
    end
  end

  private

  def check_request_from_form
    unless request.post? && params[:source] == "form"
      flash[:alert] = "Access denied"
      redirect_to root_path
    end
  end

  def set_upload
    @upload = Upload.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def upload_params
    params.require(:upload).permit(:files)
  end

  def search_params
    params.permit([ :query, :authenticity_token, :source, :controller, :action ])
  end
end

rails_app/app/views/uploads/_index_card.html.erb
<div class="bg-white dark:bg-slate-800 shadow-xl w-96 p-5"  id="upload_result_<%= upload.id %>">
  <% if upload.files.attached? %>
    <% input_file = upload.files.first %>
    <% if input_file.content_type.start_with?('image/') %>
      <div class="flex flex-col h-full"
        <!-- Flex container for spacing elements -->
        <div class="flex flex-1 flex-col justify-between">
          <!-- Image Section -->
          <div class="flex flex-col items-center mb-4 space-y-2">
            <div class="avatar">
              <div class="mask mask-squircle h-24 w-24">
                <%= image_tag input_file.variant(:thumb) %>
              </div>
            </div>
            <% if upload.files.count > 1 %>
              <% output_file = upload.files.second %>
              <% if output_file.content_type.start_with?('image/') %>
                <div class="avatar">
                  <div class="mask mask-squircle h-24 w-24">
                    <%= image_tag rails_blob_path(output_file, disposition: "inline"), alt: 'Output File thumbnail' %>
                  </div>
                </div>
              <% else %>
                <span class="text-sm">No output file attached</span>
              <% end %>
            <% else %>
              <span class="text-sm">No output file attached</span>
            <% end %>
          </div>
          <!-- Filename Section -->
          <h2 class="card-title text-lg font-semibold mb-4 text-center justify-center"><%= input_file.filename.to_s %></h2>
          <!-- Details Button Section -->
          <div class="text-center">
            <%= link_to "Details", upload_path(upload), class: "btn btn-primary btn-sm" %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

rails_app/app/views/uploads/_new.html.erb
<div class="flex flex-col items-center justify-center text-black dark:text-white">
  <%= form_with(model: @upload, local: true) do |form| %>
    <% if @upload.errors.any? %>
      <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 p-4 rounded-lg">
        <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>
        <ul>
          <% @upload.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field mb-5">
      <%= render "uploads/image_form", form: form %>
    </div>
    <div class="grid grid-cols-4 gap-4">
      <%= form.submit 'Submit', class: "text-center bg-green-500 text-black p-2 rounded-lg cursor-pointer" %>
      <p></p>
      <p></p>
      <%= link_to 'Back', uploads_path, class: 'text-center bg-violet-500 text-black p-2 rounded-lg' %>
    </div>
  <% end %>
</div>

rails_app/app/views/uploads/_no_search.html.erb
<div class="flex flex-col items-center pt-10 text-black dark:text-white" id="no-search-yet">
    <p class="text-2xl">
      Search for somethin would ya?
    </p>
  <img
    src="https://i.pinimg.com/originals/f5/48/5f/f5485f1f382d1e5d6c72a2f66cd490d9.png"
    class="w-1/4 rounded-sm" />
</div>

rails_app/app/views/uploads/_no_search_results.html.erb
<div class="flex flex-col items-center justify-center pt-10 text-black dark:text-white" id="no-search-results">
    <p class="text-2xl">
      I didn't find nothin' based on your input query - try again!
    </p>
  <img
    src="https://i.pinimg.com/originals/f5/48/5f/f5485f1f382d1e5d6c72a2f66cd490d9.png"
    class="max-w-sm rounded-sm" />
</div>

rails_app/app/views/uploads/_no_uploads.html.erb
<div class="flex flex-col items-center">
    <h1 class="text-2xl font-bold text-black dark:text-white">No uploads found!</h1>
      <p class="text-2xl text-black dark:text-white" >
        <a href="<%= new_upload_path %>" class="text-highlight underline text-black dark:text-white">Click here</a> to add a new upload.
      </p>
    <img
      src="https://i.pinimg.com/originals/f5/48/5f/f5485f1f382d1e5d6c72a2f66cd490d9.png"
      class="max-w-sm rounded-sm" />
    </img>
</div>

rails_app/app/views/uploads/_search.html.erb
<div class="flex flex-col items-center justify-center">
  <%= form_with url: search_items_uploads_path, local: true, method: :post, data: {controller: "debounce", debounce_target: "form"} do |form| %>
    <%= form.search_field :query, data: {action: "input->debounce#search"}, placeholder: 'search file names', class: "search-input-field", id: "search-box" %>
    <%= form.hidden_field :source, value: 'form' %>
  <% end %>
</div>
<div id="search_results" class="flex-col gap-x-5 gap-y-10"">
  <%= render "uploads/no_search" %>
</div>

rails_app/app/views/uploads/_search_results.html.erb
<div id="search-results-returned">
  <% if @uploads.present? %>
    <div class="flex flex-col items-center justify-center p-5 h-full bg-white dark:bg-slate-800">
      <button 
          onclick="window.location.reload();" 
          class="btn btn-primary btn-sm bg-fuchsia-400 text-black p-3 rounded-xl"
          aria-label="Refresh"
        >
        <i class="fas fa-sync"></i>
      </button>
      <div class="block 2xl:hidden">
        <% @uploads.each_with_index do |upload, index| %>
          <div class="bg-gray-100 dark:bg-slate-700 shadow-lg text-slate-900 dark:text-white p-3 mt-5 rounded-xl">
            <div class="w-full h-1/2 rounded-xl">
              <% if upload.files.attached? %>
                <% input_file = upload.files.first %>
                <% if input_file.representable? %>
                  <div class="flex items-center gap-3">
                    <div class="avatar">
                      <div class="w-12 h-12 mask mask-squircle">
                        <a href="<%= rails_blob_path(input_file, disposition: "attachment") %>" 
                                      class="venobox" 
                                      data-title="input file (<%= input_file.filename.to_s %>)" 
                                      data-gall="gal-<%= index %>" 
                                      data-vbtype="video">
                          <%= image_tag input_file.preview(:thumb) %>
                        </a>
                      </div>
                    </div>
                    <div>
                      <div class="font-bold"><%= input_file.filename.to_s %></div>
                      <div class="text-sm opacity-50"><%= input_file.created_at.to_s %></div>
                    </div>
                  </div>
                  <% if upload.files.attached? && upload.files.count > 1 %>
                    <% output_file = upload.files.second %>
                    <div>
                      <% begin %>
                        <% json_content = output_file.download %>
                        <% parsed_json = JSON.parse(json_content) %>
                        <% transcript = parsed_json['transcript']&.gsub(/\t/, '').strip  || 'No transcript key found' %>
                        <textarea rows="3" cols="10" readonly style="width: 100%; max-width: 600px; height: auto; text-align: left;" class="text-black"> <%= transcript %> </textarea>
                        <% rescue JSON::ParserError %>
                        <p>Invalid JSON file.</p>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
              <div>
                <%= link_to "Details", upload_path(upload), class: "transition bg-violet-500 px-2 py-1 rounded-lg ease-in-out delay-100 hover hover:bg-violet-500 hover:text-white text-black btn btn-sm" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="hidden w-auto 2xl:block bg-gray-100 dark:bg-slate-700 shadow-lg text-slate-900 dark:text-white p-3 mt-5 rounded-xl">
        <table class="table">
          <thead>
            <tr>
              <th><label><input type="checkbox" class="checkbox hidden" disabled></label></th>
              <th>Input</th>
              <th>Output</th>
              <th>Details</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @uploads.each_with_index do |upload, index| %>
              <% if upload.files.attached? %>
                <% input_file = upload.files.first %>
                <% if input_file.representable? %>
                  <tr>
                    <th>
                      <input type="checkbox" 
                   class="checkbox hidden" 
                   id="checkbox-<%= index %>"
                   disabled>
                    </th>
                    <td>
                      <div class="flex items-center gap-3">
                        <div class="avatar mb-12">
                          <div class="w-12 h-12 mask mask-squircle">
                            <a href="<%= rails_blob_path(input_file, disposition: "attachment") %>" 
                                      class="venobox" 
                                      data-title="input file (<%= input_file.filename.to_s %>)" 
                                      data-gall="gal-<%= index %>" 
                                      data-vbtype="video">
                              <%= image_tag input_file.preview(:thumb) %>
                            </a>
                          </div>
                        </div>
                        <div>
                          <div class="font-bold"><%= input_file.filename.to_s %></div>
                          <div class="text-sm opacity-50"><%= input_file.created_at.to_s %></div>
                        </div>
                      </div>
                    </td>
                    <td>
                      <% if upload.files.attached? && upload.files.count > 1 %>
                        <% output_file = upload.files.second %>
                        <div>
                          <% begin %>
                            <% json_content = output_file.download %>
                            <% parsed_json = JSON.parse(json_content) %>
                            <% transcript = parsed_json['transcript']&.gsub(/\t/, '').strip  || 'No transcript key found' %>
                            <textarea rows="3" cols="10" readonly style="width: 100%; max-width: 600px; height: auto; text-align: left;" class="text-black"> <%= transcript %> </textarea>
                            <% rescue JSON::ParserError %>
                            <p>Invalid JSON file.</p>
                          <% end %>
                        </div>
                      <% end %>
                    </td>
                    <th class="px-5">
                      <%= link_to "Details", upload_path(upload), class: "transition bg-violet-500 px-2 py-1 rounded-lg ease-in-out delay-100 hover hover:bg-violet-500 hover:text-white text-black btn btn-sm" %>
                    </th>
                  </tr>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
          <tfoot>
            <tr>
              <th></th>
              <th>Input</th>
              <th>Output</th>
              <th>Details</th>
              <th></th>
            </tr>
          </tfoot>
        </table>
      </div>
    <% else %>
      <%= render 'uploads/no_search_results' %>
    <% end %>
  </div>
</div>

rails_app/app/views/uploads/_show.html.erb
<div class="w-1/2 bg-slate-300 dark:bg-slate-700 p-2 rounded-2xl text-black dark:text-white mx-auto">
  <% if @upload.files.attached? %>
    <div class="flex flex-row">
      <% input_file = @upload.files.first %>
      <% if input_file.representable? %>
        <div class="p-5">
          <div class="grid grid-flow-row justify-center">
            <h4>Input</h4>
            <video id="videoElement" controls style="width: 100%; height: auto;">
              <source src="<%= url_for(input_file) %>" type="<%= input_file.content_type %>">
              Your browser does not support the video tag.
            </video>
          </div>
        </div>
      <% else %>
        <h4>Input</h4>
        <div class="justify-end">
          <p>No input file attached.</p>
        </div>
      <% end %>
      <div class="p-5">
        <% if @upload.files.attached? && @upload.files.count > 1 %>
          <div class="grid grid-flow-row justify-center">
            <h4">Output</h4>
            <% output_file = @upload.files.second %>
            <% begin %>
              <% json_content = output_file.download %>
              <% parsed_json = JSON.parse(json_content) %>
              <textarea id="jsonTextarea" rows="12" cols="50" readonly style="width: 100%; max-width: 100%; height: auto; white-space: pre-wrap; display: block;" class="text-black"><%= JSON.pretty_generate(parsed_json).gsub(/\t/, '') %></textarea>
              <% rescue JSON::ParserError %>
              <p>Invalid JSON file.</p>
            <% end %>
          </div>
        <% else %>
          <h4>Output</h4>
          <div class="justify-end">
            <p>No output file attached.</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="flex gap-4 mt-4 justify-center">
      <%= link_to 'Back', uploads_path, class:  'bg-blue-500 text-white px-3 py-2 text-center rounded-xl hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-500' %>
      <% if @upload.user_id == current_user.id %>
        <%= button_to "Delete", upload_path(@upload), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: 'bg-red-500 text-white px-3 py-2 text-center rounded-xl hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500' %>
      <% end %>
      <button 
                  onclick="window.location.reload();" 
                  class="btn btn-primary btn-sm bg-fuchsia-400 text-black p-3 rounded-xl"
                  aria-label="Refresh"
                >
        <i class="fas fa-sync"></i>
      </button>
    </div>
  <% end %>
</div>

rails_app/app/views/uploads/_uploads_results.html.erb
<div id="all-uploads-results">
  <% if @uploads.present? %>
    <div class="flex flex-col items-center justify-center p-5 h-auto bg-white dark:bg-slate-800">
      <button 
          onclick="window.location.reload();" 
          class="btn btn-primary btn-sm bg-fuchsia-400 text-black p-3 rounded-xl"
          aria-label="Refresh"
        >
        <i class="fas fa-sync"></i>
      </button>
      <div class="block 2xl:hidden">
        <% @uploads.each_with_index do |upload, index| %>
          <div class="bg-gray-100 dark:bg-slate-700 shadow-lg text-slate-900 dark:text-white p-3 mt-5 rounded-xl" id="upload_result_<%= upload.id %>">
            <div class="w-auto h-1/2 rounded-xl">
              <% if upload.files.attached? %>
                <% input_file = upload.files.first %>
                <% if input_file.representable? %>
                  <div class="flex items-center gap-3">
                    <div class="avatar">
                      <div class="w-12 h-12 mask mask-squircle">
                        <a href="<%= rails_blob_path(input_file, disposition: "attachment") %>" 
                                      class="venobox" 
                                      data-title="input file (<%= input_file.filename.to_s %>)" 
                                      data-gall="gal-<%= index %>" 
                                      data-vbtype="video">
                          <%= image_tag input_file.preview(:thumb) %>
                        </a>
                      </div>
                    </div>
                    <div>
                      <div class="font-bold"><%= input_file.filename.to_s %></div>
                      <div class="text-sm opacity-50"><%= input_file.created_at.to_s %></div>
                    </div>
                  </div>
                  <% if upload.files.attached? && upload.files.count > 1 %>
                    <% output_file = upload.files.second %>
                    <div>
                      <% begin %>
                        <% json_content = output_file.download %>
                        <% parsed_json = JSON.parse(json_content) %>
                        <% transcript = parsed_json['transcript']&.gsub(/\t/, '').strip  || 'No transcript key found' %>
                        <textarea rows="3" cols="10" readonly style="width: 100%; max-width: 600px; height: auto; text-align: left;" class="text-black"> <%= transcript %> </textarea>
                        <% rescue JSON::ParserError %>
                        <p>Invalid JSON file.</p>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
              <div>
                <%= link_to "Details", upload_path(upload), class: "transition bg-violet-500 px-2 py-1 rounded-lg ease-in-out delay-100 hover hover:bg-violet-500 hover:text-white text-black btn btn-sm" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="hidden w-auto 2xl:block bg-gray-100 dark:bg-slate-700 shadow-lg text-slate-900 dark:text-white p-3 mt-5 rounded-xl">
        <div data-controller="file-sort">
          <div class="flex justify-center gap-3">
            <button data-action="click->file-sort#sortAscending" class="btn">&#9650;</button>
            <button data-action="click->file-sort#sortDescending" class="btn">&#9660;</button>
          </div>
          <div class="overflow-x-auto flex flex-col items-center justify-center">
            <table class="table" data-file-sort-target="fileList">
              <thead>
                <tr>
                  <th><label><input type="checkbox" class="checkbox hidden" disabled></label></th>
                  <th>Input</th>
                  <th>Output</th>
                  <th>Details</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @uploads.each_with_index do |upload, index| %> <!-- Reverse order here -->
                  <% if upload.files.attached? %>
                    <% input_file = upload.files.first %>
                    <% if input_file.representable? %>
                      <tr data-created-at="<%= input_file.created_at.iso8601 %>">
                        <th>
                          <input type="checkbox" 
                   class="checkbox hidden" 
                   id="checkbox-<%= index %>"
                   disabled>
                        </th>
                        <td>
                          <div class="flex items-center gap-5" id="upload_result_<%= upload.id %>">
                            <div class="avatar mb-12">
                              <div class="w-12 h-12 mask mask-squircle">
                                <a href="<%= rails_blob_path(input_file, disposition: "attachment") %>" 
                                      class="venobox" 
                                      data-title="input file (<%= input_file.filename.to_s %>)" 
                                      data-gall="gal-<%= index %>" 
                                      data-vbtype="video">
                                  <%= image_tag input_file.preview(:thumb) %>
                                </a>
                              </div>
                            </div>
                            <div>
                              <div class="font-bold"><%= input_file.filename.to_s %></div>
                              <div class="text-sm opacity-50"><%= input_file.created_at.to_s %></div>
                            </div>
                          </div>
                        </td>
                        <td>
                          <% if upload.files.attached? && upload.files.count > 1 %>
                            <% output_file = upload.files.second %>
                            <div>
                              <% begin %>
                                <% json_content = output_file.download %>
                                <% parsed_json = JSON.parse(json_content) %>
                                <% transcript = parsed_json['transcript']&.gsub(/\t/, '').strip  || 'No transcript key found' %>
                                <textarea rows="3" cols="10" readonly style="width: 100%; max-width: 600px; height: auto; text-align: left;" class="text-black"> <%= transcript %> </textarea>
                                <% rescue JSON::ParserError %>
                                <p>Invalid JSON file.</p>
                              <% end %>
                            </div>
                          <% end %>
                        </td>
                        <th class="px-5">
                          <%= link_to "Details", upload_path(upload), class: "transition bg-violet-500 px-2 py-1 rounded-lg ease-in-out delay-100 hover hover:bg-violet-500 hover:text-white text-black btn btn-sm" %>
                        </th>
                      </tr>
                    <% end %>
                  <% end %>
                <% end %>
              </tbody>
              <tfoot>
                <tr>
                  <th></th>
                  <th>Input</th>
                  <th>Output</th>
                  <th>Status</th>
                  <th></th>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
      <div class="pagy-nav flex my-5 mb-5 pb-5 justify-center center-content">
        <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
      </div>
    </div>
  <% else %>
    <%= render "uploads/no_uploads" %>
  <% end %>
</div>

rails_app/app/views/uploads/destroy.html.erb
<h1>Show page for Upload</h1>
<% if @upload.files.attached? %>
  <% @upload.files.each do |file| %>
    <%= image_tag file, alt: 'Uploaded Image', style: 'max-width: 100%; height: auto;' %>
  <% end %>
<% else %>
  <p>No files attached.</p>
<% end %>
<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %> |
<%= link_to 'Delete', upload_path(@upload), method: :delete, data: { confirm: 'Are you sure you want to delete this upload?' }, class: 'button' %>

rails_app/app/views/uploads/index.html.erb
<%= render partial: "shared/inverse_functionality_style_layout", locals: { inner_partial: "uploads/uploads_results" , uploads: @uploads} %>

rails_app/app/views/uploads/new.html.erb
<%= render partial: "shared/inverse_functionality_style_layout", locals: { inner_partial: "uploads/new"} %>

rails_app/app/views/uploads/search.html.erb
<%= render partial: "shared/inverse_functionality_style_layout", locals: { inner_partial: "uploads/search"} %>

rails_app/app/views/uploads/show.html.erb
<%= render partial: "shared/inverse_functionality_style_layout", locals: { inner_partial: "uploads/show" , uploads: @uploads} %>